from pathlib import Path
import shutil
root=Path(__file__).resolve().parents[2];g=root/'godot-game';out=root/'exports/Reference_Motion_Mac_20260912';base=out/'baseline'
p=(base/'reference_sword_motion.gd').read_text().replace('## Optional Windows-authored samples.','## Authored camera-space samples (MacBook production; legacy Windows supported).')
p=p.replace('str(manifest.get("status", "")) != "authored_windows_output"','str(manifest.get("status", "")) not in ["authored_windows_output", "authored_macos_output"]')
p=p.replace('str(provenance.get("execution_os", "")) != "Windows"','str(provenance.get("execution_os", "")) != ("Darwin" if str(manifest.get("status", "")) == "authored_macos_output" else "Windows")')
p=p.replace('requires successful Windows authoring provenance.','requires successful matching authoring provenance.')
(g/'scripts/reference_sword_motion.gd').write_text(p)
p=(base/'player.gd').read_text()
p=p.replace('if _movement_grounded and planar_speed > WALK_SPEED:\n\t\t_movement_run_time += delta * clampf(planar_speed / SPRINT_SPEED, 0.0, 1.5)','if _movement_grounded and planar_speed > 0.01:\n\t\t_movement_run_time += delta * clampf(planar_speed / WALK_SPEED, 0.0, 1.0)')
p=p.replace('var authored_amount := 1.0 if _movement_phase != "grounded" else','var authored_amount := 1.0 if _movement_phase != "grounded" or REFERENCE_MOTION.has_track("walk") else')
p=p.replace('if authored and phase != "ready": return target','if authored and (phase != "ready" or REFERENCE_MOTION.has_track("walk")): return target')
p=p.replace('func _shield_corner_offset() -> Vector3:\n','func _shield_corner_offset() -> Vector3:\n\t# Complete Mac clips already contain their final camera framing.\n\tif REFERENCE_MOTION.has_track("walk", "shield"): return Vector3.ZERO\n')
p=p.replace('\tif REFERENCE_MOTION.has_track("run", track):\n\t\tvar running', '\tif REFERENCE_MOTION.has_track("walk", track):\n\t\tbase = base.interpolate_with(REFERENCE_MOTION.sample("walk", _movement_run_time, track), MOTION.smooth_phase(clampf(_motion_speed / WALK_SPEED, 0.0, 1.0)))\n\tif REFERENCE_MOTION.has_track("run", track):\n\t\tvar running')
p=p.replace('\t\telse:\n\t\t\tvar running := clampf((_motion_speed - WALK_SPEED)', '\t\telse:\n\t\t\tif REFERENCE_MOTION.has_right_arm("walk"):\n\t\t\t\tresult = _mix_reference_arms(result, REFERENCE_MOTION.sample_right_arm("walk", _movement_run_time), MOTION.smooth_phase(clampf(_motion_speed / WALK_SPEED, 0.0, 1.0)))\n\t\t\tvar running := clampf((_motion_speed - WALK_SPEED)')
(g/'scripts/player.gd').write_text(p)
shutil.copyfile(root/'asset-staging/reference_motion_mac_20260912/iteration_01/motion_manifest.json',g/'assets/animations/reference_sword_motion/motion_manifest.json')
p=(base/'reference_sword_motion_preview.gd').read_text().replace('const SEQUENCE_IDS := ["idle", "run"','const SEQUENCE_IDS := ["idle", "walk", "run"')
p=p.replace('sequence_id == "run" else Vector2.ZERO','sequence_id in ["walk", "run"] else Vector2.ZERO')
p=p.replace('if sprinting:\n\t\tfor step in range(PHYSICS_FPS):\n\t\t\tawait _advance_physics(player, movement, true)','if sequence_id in ["walk", "run"]:\n\t\tfor step in range(PHYSICS_FPS):\n\t\t\tawait _advance_physics(player, movement, sprinting)')
p=p.replace('if sequence_id != "idle" and not sprinting','if sequence_id not in ["idle", "walk", "run"]')
p=p.replace('if sequence_id == "run":\n\t\tduration', 'if sequence_id in ["walk", "run"]:\n\t\tduration')
p=p.replace('Windows-authored','authored').replace('Windows trajectories','Mac trajectories')
(g/'tests/reference_sword_motion_preview.gd').write_text(p)
