extends SceneTree

var room: Node3D
var failures: Array[String] = []
var audio_bus := -1


func _init() -> void:
	call_deferred("_run")


func _run() -> void:
	if DisplayServer.get_name() == "headless":
		push_error("Stress preview requires a real rendering display and mouse capture")
		quit(1)
		return
	root.size = Vector2i(1280, 720)
	room = (load("res://test_room.tscn") as PackedScene).instantiate()
	root.add_child(room)
	current_scene = room
	room.set_process_unhandled_input(false)
	room.player.set_process_unhandled_input(false)
	await process_frame
	await process_frame
	room.run_feature("stress_vision")
	for _frame in range(40):
		await physics_frame
		if room.player.is_on_floor() and room.player.trap_lockout <= 0.0:
			break
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path("res://artifacts/visual_qa"))
	room.set_process(false)
	room.camp.set_process(false)
	var effects: StressPerception = room.stress_effects
	effects.set_process(false)
	effects.rng.seed = 77621
	room._update_stress_presentation()
	_check(Input.mouse_mode == Input.MOUSE_MODE_CAPTURED and effects._can_perceive(), "native preview must use actual captured input and the unmodified production perception guard")
	await _capture("stress_test_fixture.png")
	if OS.get_environment("STRESS_QA_INTERACTIVE") == "1":
		room.set_process(true)
		effects.set_process(true)
		room.set_process_unhandled_input(true)
		room.player.set_process_unhandled_input(true)
		return
	if not effects._can_perceive():
		await _finish()
		return
	# Inspect actual audio mixed by Godot, not only a generated byte buffer.
	audio_bus = AudioServer.bus_count
	AudioServer.add_bus()
	AudioServer.set_bus_name(audio_bus, "StressQACapture")
	var capture := AudioEffectCapture.new()
	capture.buffer_length = 1.0
	AudioServer.add_bus_effect(audio_bus, capture)
	effects.audio_player.bus = "StressQACapture"
	effects.clear_effects()
	effects.advance(2.05)
	_check(effects.event_count > 0 and effects.audio_player.playing and effects.audio_player.stream is AudioStreamWAV, "native scheduler must naturally play a real hallucination after its entry delay")
	await _check_mixed_audio(capture, "natural scheduled audio")
	for kind: String in ["whisper", "footsteps"]:
		effects.clear_effects()
		capture.clear_buffer()
		_check(effects.trigger_event(kind), "native production sound trigger accepted: " + kind)
		await _check_mixed_audio(capture, kind)
	effects.clear_effects()
	var before_health: float = room.player.health
	var before_enemies: int = room.enemies_alive
	_check(effects.trigger_event("vision"), "native production vision must find visible clear ground")
	effects.advance(0.28)
	_check(is_instance_valid(effects.ghost), "actual shadow silhouette must persist long enough to be seen")
	if is_instance_valid(effects.ghost):
		var screen: Vector2 = room.player.camera.unproject_position(effects.ghost.global_position + Vector3.UP)
		_check(root.get_visible_rect().has_point(screen), "hallucination must be within the camera view")
		print("STRESS PREVIEW ghost screen center: ", screen)
	await _capture("stress_peripheral_vision.png")
	_check(is_equal_approx(room.player.health, before_health) and room.enemies_alive == before_enemies, "rendered vision must not alter real combat state")
	room._open_inventory()
	await _capture("stress_inventory.png")
	_check(not effects.active and effects.ghost == null and not effects.audio_player.playing, "inventory must immediately stop perceived enemies and sounds")
	_check(is_equal_approx(room.inventory_overlay.stress_bar.value, 90.0), "inventory stress matches the real session")
	room._close_inventory()
	_key(KEY_C)
	_check(room.camp.is_open() and paused, "real C input must open a stress-only camp")
	if room.camp.is_open():
		await _capture("stress_camp_plan.png")
		var panel := room.camp.overlay.panel_root as Control
		_check(root.get_visible_rect().encloses(panel.get_global_rect()), "stress camp panel fits the native viewport")
		room.camp.overlay.action_buttons["rest"].pressed.emit()
		room.camp.advance_rest(8.0)
		_check(is_equal_approx(ExpeditionSession.stress, 72.0), "real rest button relieves stress by eighteen")
		room.camp.overlay.action_buttons["rest"].pressed.emit()
		room.camp.advance_rest(8.0)
		_check(is_equal_approx(ExpeditionSession.stress, 54.0), "a second paid rest moves stress below the audio threshold")
		await _capture("stress_camp_recovered.png")
		room.camp.overlay.leave_button.pressed.emit()
	room._update_stress_presentation()
	effects.advance(0.1)
	_check(effects.ghost == null and not effects.audio_player.playing, "relief below sixty leaves no vision or hallucinated audio")
	await _capture("stress_return_to_dungeon.png")
	room._show_test_panel()
	room._select_category("생존")
	await _capture("stress_test_menu.png")
	await _finish()


func _check_mixed_audio(capture: AudioEffectCapture, label: String) -> void:
	await create_timer(0.35).timeout
	var samples := capture.get_buffer(capture.get_frames_available())
	var energy := 0.0
	for sample in samples:
		energy += sample.length_squared()
	_check(samples.size() > 0 and energy > 0.000001, "actual native output contains non-silent mixed audio: " + label)
	print("STRESS PREVIEW audio ", label, ": frames=", samples.size(), " energy=", energy)


func _finish() -> void:
	room.cancel_camp("", false)
	room.queue_free()
	await process_frame
	root.get_node("TestRoomSandbox").finish()
	if audio_bus >= 0:
		AudioServer.remove_bus(audio_bus)
	paused = false
	Input.mouse_mode = Input.MOUSE_MODE_VISIBLE
	if failures.is_empty():
		print("STRESS PREVIEW PASS: real input capture, naturally scheduled and mixed positional audio, harmless peripheral vision, inventory cleanup, actual camp buttons/recovery and rendered survival test catalog")
		quit(0)
	else:
		for failure in failures:
			push_error("STRESS PREVIEW FAIL: " + failure)
		quit(1)


func _key(key: Key) -> void:
	var event := InputEventKey.new()
	event.physical_keycode = key
	event.pressed = true
	room._unhandled_input(event)


func _capture(file_name: String) -> void:
	await process_frame
	await process_frame
	RenderingServer.force_draw(false)
	var result := root.get_texture().get_image().save_png(ProjectSettings.globalize_path("res://artifacts/visual_qa/" + file_name))
	_check(result == OK, "could not save preview: " + file_name)


func _check(condition: bool, message: String) -> void:
	if not condition:
		failures.append(message)
